### PR TITLE
Update SDL2 bindings to SDL 2.0.6, and also other SDL2 libs

### PR DESCRIPTION
**Pull request by rversteegen**
I'm not sure whether to send a pull request for raw or master or both. Naturally, one of the two parents of the master commit is the raw branch.

### CODE REVIEW

**Comment by dkl** [comment]
I've merged the changes to `raw`. Afterwards it can be merged to `master`.

Looks like `_SDLNet_Write16`/`_SDLNet_Write32` are translated differently now; the replacements from `sdl.replacements` don't match anymore. Is that ok or should we fix it?

**Comment by rversteegen** [comment]
I see you already fixed the rules for `_SDLNet_Write{16,32}`. I don't understand why the typoed version used to match before but stopped working (if I understand correctly).

SDL 2.0.8 has now been released, along with new versions of other libraries, so I can update to that.

**Comment by dkl** [comment]
Well, I fixed the `end sco` typo in the FB macro, but the replacements rule still didn't match. Something must have changed about the C version. But oh well, since the auto-translation seems ok, and these macros don't seem to be intended for public use anyways, I removed the replacements.

**Comment by rversteegen** [comment]
Those macros are intended for public use. Earlier in the header is:
```
#define SDLNet_Write16(value, areap) _SDLNet_Write16(value, areap)
#define SDLNet_Write32(value, areap) _SDLNet_Write32(value, areap)
```
I'll try to fix the replacements, since the macros are more performant under -gen gas.
Oh, is there any reason those one-line statements like
``#define _SDLNet_Write32(value, areap) scope : *cptr(Uint32 ptr, areap) = SDL_Swap32(value) : end scope``
are inside a scope block? AFAIK the scope is useless.

**Comment by rversteegen** [comment]
Here's a couple more commits for raw.

Note: When merging into master, there is one small conflict in SDL.bi (where you have to delete an instance of `function SDL_QuitRequested()`). This weird discrepancy between raw and master wasn't caused by any of my commits, so I'm not inclined to spend time investigating it.

**Comment by dkl** [comment]
> Oh, is there any reason those one-line statements like
> #define _SDLNet_Write32(value, areap) scope : *cptr(Uint32 ptr, areap) = SDL_Swap32(value) : end scope
> are inside a scope block? AFAIK the scope is useless.

The Scope protects the assignment from accidentally being treated as comparison, e.g. if someone did `if _SDLNet_Write32(...) then`

**Comment by dkl** [comment]
Thanks for the updates by the way, looks good. May I suggest updating the copyright year in fbteam.txt? Seems like that would be appropriate in this case.

**Comment by rversteegen** [comment]
OK, I did so. No other changes.

**Pull request merged**
